<?php

if ( ! defined( 'ABSPATH' ) ) { exit; }

$error = false;
$math_one = mt_rand(10,99);
$math_two = mt_rand(1,9);	
$nonce = wp_nonce_field( 'sform_nonce_action', 'sform_nonce', true, false );
$empty_data = array( 'name' => '','lastname' => '','email' => '','phone' => '','subject' => '','message' => '','consent' => '','captcha' => '','captcha_one' => '','captcha_two' => '','url' => '','telephone' => '' );
$data = apply_filters( 'sform_validation', $empty_data );
$form_error = array_slice($data, 12, 1);
$errors_string = implode(" ", $form_error);
$errors_list = array_filter(explode(";", $errors_string));
$errors_counter = count($errors_list);
$error_class = ! empty($data['error']) ? array_flip($errors_list) : '';
$characters_length = ! empty( $settings['characters_length'] ) ? esc_attr($settings['characters_length']) : 'true';
$introduction_text = isset ( $attributes['introduction_text'] ) ? stripslashes(wp_kses_post($attributes['introduction_text'])) : esc_attr__( 'Please fill out the form below and we will get back to you as soon as possible. Mandatory fields are marked with (*).', 'simpleform' );
$bottom_text = ! empty( $attributes['bottom_text'] ) ? stripslashes(wp_kses_post($attributes['bottom_text'])) : '';
$required_sign = ! empty( $attributes['required_sign'] ) ? esc_attr($attributes['required_sign']) : 'true';
$required_word = ! empty( $attributes['required_word'] ) ? esc_attr($attributes['required_word']) : '';
$word_position = ! empty( $attributes['word_position'] ) ? esc_attr($attributes['word_position']) : 'required';
$name_field = ! empty( $attributes['name_field'] ) ? esc_attr($attributes['name_field']) : 'visible';
$name_requirement = ! empty( $attributes['name_requirement'] ) ? esc_attr($attributes['name_requirement']) : 'required';
$name_maxlength = isset( $attributes['name_maxlength'] ) ? esc_attr($attributes['name_maxlength']) : '0';
$name_maxlength = $name_maxlength != 0 ? ' maxlength="'.$name_maxlength.'"' : '';
$lastname_length = isset( $attributes['lastname_minlength'] ) ? esc_attr($attributes['lastname_minlength']) : '2';
$lastname_maxlength = isset( $attributes['lastname_maxlength'] ) ? esc_attr($attributes['lastname_maxlength']) : '0';
$lastname_maxlength = $lastname_maxlength != 0 ? ' maxlength="'.$lastname_maxlength.'"' : '';
$subject_maxlength = isset( $attributes['subject_maxlength'] ) ? esc_attr($attributes['subject_maxlength']) : '0';
$subject_maxlength = $subject_maxlength != 0 ? ' maxlength="'.$subject_maxlength.'"' : '';
$message_maxlength = isset( $attributes['message_maxlength'] ) ? esc_attr($attributes['message_maxlength']) : '0';
$message_maxlength = $message_maxlength != 0 ? 'maxlength="'.$message_maxlength.'"' : '';
$email_field = ! empty( $attributes['email_field'] ) ? esc_attr($attributes['email_field']) : 'visible';
$email_requirement = ! empty( $attributes['email_requirement'] ) ? esc_attr($attributes['email_requirement']) : 'required';
$subject_field = ! empty( $attributes['subject_field'] ) ? esc_attr($attributes['subject_field']) : 'visible';
$subject_requirement = ! empty( $attributes['subject_requirement'] ) ? esc_attr($attributes['subject_requirement']) : 'required';
$captcha_field = ! empty( $attributes['captcha_field'] ) ? esc_attr($attributes['captcha_field']) : 'hidden';            
$name_label = ! empty( $attributes['name_label'] ) ? stripslashes(esc_attr($attributes['name_label'])) : esc_attr__( 'Name', 'simpleform' );
$name_field_requirement = $name_requirement == 'required' ? 'true' : 'false';
$required_name_sign = (! isset($error_class['name']) && ! isset($error_class['name_invalid']) && ! empty(esc_attr($data['name']))) || $name_requirement != 'required' || $required_sign != 'true' ? '' : '&lowast;';
$required_name = ( $required_sign == 'true' && $name_field_requirement == 'true' ) || ( $required_sign != 'true' && $name_field_requirement == 'true' && $word_position == 'required' ) || ( $required_sign != 'true' && $name_field_requirement != 'true' && $word_position != 'required' ) ? '' : 'd-none';
$required_name_word = (! isset($error_class['name']) && ! isset($error_class['name_invalid']) && ! empty(esc_attr($data['name']))) || ( $required_sign != 'true' && $name_requirement == 'required' && $word_position != 'required' ) || ( $required_sign != 'true' && $name_requirement != 'required' && $word_position == 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_name_label = $required_sign == 'true' ? '<span class="'.$required_name.'">'.$required_name_sign.'</span>' : '<span class="word '.$required_name.'">'.$required_name_word.'</span>';
$label_position = ! empty( $attributes['label_position'] ) ? esc_attr($attributes['label_position']) : 'inline';
$row_label = $label_position == 'inline' ? 'row' : '';
$label_class = $label_position == 'inline' ? 'class="col-sm-2"' : '';
$wrap_class = $label_position == 'inline' ? 'col-sm-10' : '';
$inline_class = $label_position == 'inline' ? 'col-sm-10' : '';
$name_field_label = ! empty( $attributes['name_visibility'] ) && $attributes['name_visibility'] == 'hidden' ? '' : '<label for="sform-name" '.$label_class.'>'.$name_label.$required_name_label.'</label>';
$name_placeholder = ! empty( $attributes['name_placeholder'] ) ? esc_attr($attributes['name_placeholder']) : '';
$lastname_placeholder = ! empty( $attributes['lastname_placeholder'] ) ? esc_attr($attributes['lastname_placeholder']) : '';
$email_placeholder = ! empty( $attributes['email_placeholder'] ) ? esc_attr($attributes['email_placeholder']) : '';
$phone_placeholder = ! empty( $attributes['phone_placeholder'] ) ? esc_attr($attributes['phone_placeholder']) : '';
$subject_placeholder = ! empty( $attributes['subject_placeholder'] ) ? esc_attr($attributes['subject_placeholder']) : '';
$message_placeholder = ! empty( $attributes['message_placeholder'] ) ? esc_attr($attributes['message_placeholder']) : '';
$lastname_field = ! empty( $attributes['lastname_field'] ) ? esc_attr($attributes['lastname_field']) : 'hidden';
$lastname_alignment = ! empty( $attributes['lastname_alignment'] ) ? esc_attr($attributes['lastname_alignment']) : 'name';
$name_style = $lastname_alignment == 'name' && ( $name_field == 'visible' || $name_field == 'registered' && is_user_logged_in() || $name_field == 'anonymous' && ! is_user_logged_in() ) && ( $lastname_field == 'visible' || $lastname_field == 'registered' && is_user_logged_in() || $lastname_field == 'anonymous' && ! is_user_logged_in() ) ? 'half' : '';
$name_row_class = $name_style . ' ' . $row_label;
$lastname_label = ! empty( $attributes['lastname_label'] ) ? stripslashes(esc_attr($attributes['lastname_label'])) : esc_attr__( 'Last Name', 'simpleform' );
$lastname_requirement = ! empty( $attributes['lastname_requirement'] ) ? esc_attr($attributes['lastname_requirement']) : 'optional';
$lastname_field_requirement = $lastname_requirement == 'required' ? 'true' : 'false';
$required_lastname = ( $required_sign == 'true' && $lastname_field_requirement == 'true' ) || ( $required_sign != 'true' && $lastname_field_requirement == 'true' && $word_position == 'required' ) || ( $required_sign != 'true' && $lastname_field_requirement != 'true' && $word_position != 'required' ) ? '' : 'd-none';
$required_lastname_sign = (! isset($error_class['lastname']) && ! isset($error_class['lastname_invalid']) && ! empty(esc_attr($data['lastname']))) || $lastname_requirement != 'required' || $required_sign != 'true' ? '' : '&lowast;';
$required_lastname_word = (! isset($error_class['lastname']) && ! isset($error_class['lastname_invalid']) && ! empty(esc_attr($data['lastname']))) || ( $required_sign != 'true' && $lastname_requirement == 'required' && $word_position != 'required' ) || ( $required_sign != 'true' && $lastname_requirement != 'required' && $word_position == 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_lastname_label = $required_sign == 'true' ? '<span class="'.$required_lastname.'">'.$required_lastname_sign.'</span>' : '<span class="word '.$required_lastname.'">'.$required_lastname_word.'</span>';
$lastname_label_style = $lastname_alignment == 'name' && ! empty( $attributes['lastname_visibility'] ) && $attributes['lastname_visibility'] == 'hidden' && $attributes['name_visibility'] != 'hidden' ? '<label for="sform-lastname">&nbsp;</label>' : '';
$lastname_field_label = ! empty( $attributes['lastname_visibility'] ) && $attributes['lastname_visibility'] == 'hidden' ? $lastname_label_style : '<label for="sform-lastname" '.$label_class.'>'.$lastname_label.$required_lastname_label.'</label>';
$email_label = ! empty( $attributes['email_label']  ) ? stripslashes(esc_attr($attributes['email_label'])) : esc_attr__( 'Email', 'simpleform' );
$email_field_requirement = $email_requirement == 'required' ? 'true' : 'false';
$required_email_sign = (! isset($error_class['email']) && ! empty(esc_attr($data['email']))) || $email_requirement != 'required' || $required_sign != 'true' ? '' : '&lowast;';
$required_email = ( $required_sign == 'true' && $email_field_requirement == 'true' ) || ( $required_sign != 'true' && $email_field_requirement == 'true' && $word_position == 'required' ) || ( $required_sign != 'true' && $email_field_requirement != 'true' && $word_position != 'required' ) ? '' : 'd-none';
$required_email_word = (! isset($error_class['email']) && ! empty(esc_attr($data['email']))) || ( $required_sign != 'true' && $email_requirement == 'required' && $word_position != 'required' ) || ( $required_sign != 'true' && $email_requirement != 'required' && $word_position == 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_email_label = $required_sign == 'true' ? '<span class="'.$required_email.'">'.$required_email_sign.'</span>' : '<span class="word '.$required_email.'">'.$required_email_word.'</span>';
$phone_field = ! empty( $attributes['phone_field'] ) ? esc_attr($attributes['phone_field']) : 'hidden';
$phone_alignment = ! empty( $attributes['phone_alignment'] ) ? esc_attr($attributes['phone_alignment']) : 'email';
$email_style = $phone_alignment == 'email' && ( $email_field == 'visible' || $email_field == 'registered' && is_user_logged_in() || $email_field == 'anonymous' && ! is_user_logged_in() ) && ( $phone_field == 'visible' || $phone_field == 'registered' && is_user_logged_in() || $phone_field == 'anonymous' && ! is_user_logged_in() ) ? 'half' : '';
$email_row_class = $email_style . ' ' . $row_label;
$phone_label = ! empty( $attributes['phone_label'] ) ? stripslashes(esc_attr($attributes['phone_label'])) : esc_attr__( 'Phone', 'simpleform' );
$phone_requirement = ! empty( $attributes['phone_requirement'] ) ? esc_attr($attributes['phone_requirement']) : 'optional';
$phone_field_requirement = $phone_requirement == 'required' ? 'true' : 'false';
$required_phone = ( $required_sign == 'true' && $phone_field_requirement == 'true' ) || ( $required_sign != 'true' && $phone_field_requirement == 'true' && $word_position == 'required' ) || ( $required_sign != 'true' && $phone_field_requirement != 'true' && $word_position != 'required' ) ? '' : 'd-none';
$required_phone_sign = (! isset($error_class['phone']) && ! isset($error_class['phone_invalid']) && ! empty(esc_attr($data['phone']))) || $phone_requirement != 'required' || $required_sign != 'true' ? '' : '&lowast;';
$required_phone_word = (! isset($error_class['phone']) && ! isset($error_class['phone_invalid']) && ! empty(esc_attr($data['phone']))) || ( $required_sign != 'true' && $phone_requirement == 'required' && $word_position != 'required' ) || ( $required_sign != 'true' && $phone_requirement != 'required' && $word_position == 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_phone_label = $required_sign == 'true' ? '<span class="'.$required_phone.'">'.$required_phone_sign.'</span>' : '<span class="word '.$required_phone.'">'.$required_phone_word.'</span>';
$phone_label_style = $phone_alignment == 'email' && ! empty( $attributes['phone_visibility'] ) && $attributes['phone_visibility'] == 'hidden' && ! empty( $attributes['email_visibility'] ) && $attributes['email_visibility'] != 'hidden' ? '<label for="sform-phone">&nbsp;</label>' : '';
$phone_field_label = ! empty( $attributes['phone_visibility'] ) && $attributes['phone_visibility'] == 'hidden' ? $phone_label_style : '<label for="sform-phone" '.$label_class.'>'.$phone_label.$required_phone_label.'</label>';
$subject_label = ! empty( $attributes['subject_label'] ) ? stripslashes(esc_attr($attributes['subject_label'])) : esc_attr__( 'Subject', 'simpleform' );
$subject_field_requirement = $subject_requirement == 'required' ? 'true' : 'false';
$required_subject = ( $required_sign == 'true' && $subject_field_requirement == 'true' ) || ( $required_sign != 'true' && $subject_field_requirement == 'true' && $word_position == 'required' ) || ( $required_sign != 'true' && $subject_field_requirement != 'true' && $word_position != 'required' ) ? '' : 'd-none';
$required_subject_sign = (! isset($error_class['subject']) && ! isset($error_class['subject_invalid']) && ! empty(esc_attr($data['subject']))) || $subject_requirement != 'required' || $required_sign != 'true' ? '' : '&lowast;';
$required_subject_word = ( (! isset($error_class['subject']) && ! isset($error_class['subject_invalid']) && ! empty(esc_attr($data['subject']))) ) || ( $subject_requirement == 'required' && $word_position != 'required' ) || ( $required_sign != 'true' && $subject_requirement != 'required' && $word_position == 'required' ) || ( $required_sign != 'true' && $subject_requirement == 'required' && $word_position != 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_subject_label = $required_sign == 'true' ? '<span class="'.$required_subject.'">'.$required_subject_sign.'</span>' : '<span class="word '.$required_subject.'">'.$required_subject_word.'</span>';
$message_label = ! empty( $attributes['message_label'] ) ? stripslashes(esc_attr($attributes['message_label'])) : esc_attr__( 'Message', 'simpleform' );
$required_message_sign = ! isset($error_class['message']) && ! isset($error_class['message_invalid']) && ! empty(esc_attr($data['message'])) || $required_sign != 'true' ? '' : '&lowast;';
$required_message_word = ( ! isset($error_class['message']) && ! isset($error_class['message_invalid']) && ! empty(esc_attr($data['message']))) || ( $required_sign != 'true' && $word_position != 'required' ) || $required_sign == 'true' ? '' : $required_word;
$required_message_label = $required_sign == 'true' ? '<span>'.$required_message_sign.'</span>' : '<span class="word">'.$required_message_word.'</span>';
$email_field_label = ! empty( $attributes['email_visibility'] ) && $attributes['email_visibility'] == 'hidden' ? '' : '<label for="sform-email" '.$label_class.'>'.$email_label.$required_email_label.'</label>';
$subject_field_label = ! empty( $attributes['subject_visibility'] ) && $attributes['subject_visibility'] == 'hidden' ? '' : '<label for="sform-subject" '.$label_class.'>'.$subject_label.$required_subject_label.'</label>';
$message_field_label = ! empty( $attributes['message_visibility'] ) && $attributes['message_visibility'] == 'hidden' ? '' : '<label for="sform-message" '.$label_class.'>'.$message_label.$required_message_label.'</label>';
$consent_field = ! empty( $attributes['consent_field'] ) ? esc_attr($attributes['consent_field']) : 'visible';
$checkbox_requirement = ! empty( $attributes['consent_requirement'] ) ? esc_attr($attributes['consent_requirement']) : 'required'; 
$required_consent = $checkbox_requirement == 'required' ? '' : 'd-none';
$checkbox_value = ! empty(esc_attr($data['consent'])) ? esc_attr($data['consent']) : 'false';
$required_consent_sign = (! isset($error_class['consent']) && esc_attr($data['consent']) == 'true') || $required_sign != 'true' || $checkbox_requirement != 'required' ? '' : '&lowast;';
$required_consent_label = '<span class="'.$required_consent.'">'.$required_consent_sign.'</span>';
$consent_label = ! empty( $attributes['consent_label'] ) ? stripslashes(wp_kses_post($attributes['consent_label'])) : esc_attr__( 'I have read and consent to the privacy policy', 'simpleform' );
$captcha_label = ! empty( $attributes['captcha_label'] ) ? stripslashes(esc_attr($attributes['captcha_label'])) : esc_attr__( 'I\'m not a robot', 'simpleform' );
$captcha_one = $captcha_field != 'hidden' && $data['captcha_one'] != '' ? esc_attr($data['captcha_one']) : esc_attr( $math_one );
$captcha_two = $captcha_field != 'hidden' && $data['captcha_two'] != '' ? esc_attr($data['captcha_two']) : esc_attr( $math_two );
$captcha_hidden = '<input id="captcha_one" type="hidden" name="captcha_one" value="'.$captcha_one .'"/><input id="captcha_two" type="hidden" name="captcha_two" value="'. $captcha_two .'"/>';
$captcha_question = $captcha_one . '&nbsp;&nbsp;+&nbsp;&nbsp;' . $captcha_two.'&nbsp;&nbsp;=';
$required_captcha_sign = (! isset($error_class['captcha']) && ! empty(esc_attr($data['captcha']))) || $required_sign != 'true' ? '' : '&lowast;';
$required_captcha_label = '<span>'.$required_captcha_sign.'</span>';
$form_id = $atts_array['form'] == '0' ? '': '<input type="hidden" id="form-id" name="form-id" value="'. $atts_array['form'] .'" />';
$form_attributes = $atts_array['widget_attributes'] == '0' ? '': '<input type="hidden" id="widget-attributes" name="widget-attributes" value="'. $atts_array['widget_attributes'] .'" />';
$form_settings = $atts_array['widget_settings'] == '0' ? '': '<input type="hidden" id="widget-settings" name="widget-settings" value="'. $atts_array['widget_settings'] .'" />';
$hidden_fields = '<div class="d-none">'.$nonce.$form_id.$form_attributes.$form_settings.'</div><div class="carrots"><label for="name"></label><input type="text" name="url" id="name" placeholder="Your not human url here" value="" tabindex="-1" autocomplete="off" /><label for="telephone"></label><input type="text" id="telephone" name="telephone" placeholder="Your not human telephone here" value="" tabindex="-1" autocomplete="off" /></div>';
$submit_label = ! empty($attributes['submit_label'] ) ? stripslashes(esc_attr($attributes['submit_label'])) : esc_attr__( 'Submit', 'simpleform' );
$name_length = isset( $attributes['name_minlength'] ) ? esc_attr($attributes['name_minlength']) : '2';
$name_regex = ! empty( $settings['name_regex'] ) ? $settings['name_regex'] : '/^[^0-9\"\/:!?\#$%&()_=+*{}\[\];|<\@>]+$/';
$error_invalid_name_label = ! empty( $settings['invalid_name'] ) ? stripslashes(esc_attr($settings['invalid_name'])) : esc_attr__( 'The name contains invalid characters', 'simpleform' );
$lastname_numeric_error = $characters_length == 'true' && ! empty( $settings['incomplete_lastname'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_lastname']) == $lastname_length ? stripslashes(esc_attr($settings['incomplete_lastname'])) : sprintf( __('Please enter at least %d characters', 'simpleform' ), $lastname_length );
$lastname_generic_error = $characters_length != 'true' && ! empty( $settings['incomplete_lastname'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_lastname']) == '' ? stripslashes(esc_attr($settings['incomplete_lastname'])) : esc_attr__('Please type your full last name', 'simpleform' );
$error_lastname_label = $characters_length == 'true' ? $lastname_numeric_error : $lastname_generic_error;
$lastname_regex = ! empty( $settings['lastname_regex'] ) ? $settings['lastname_regex'] : '/^[^0-9\"\/:!?\#$%&()_=+*{}\[\];|<\@>]+$/';
$error_invalid_lastname_label = ! empty( $settings['invalid_lastname'] ) ? stripslashes(esc_attr($settings['invalid_lastname'])) : esc_attr__( 'The last name contains invalid characters', 'simpleform' );
$error_phone_label = ! empty( $settings['invalid_phone'] ) ? stripslashes(esc_attr($settings['invalid_phone'])) : esc_attr__( 'The phone number contains invalid characters', 'simpleform' );
$subject_length = ! empty( $settings['subject_length'] ) ? esc_attr($settings['subject_length']) : '10';
$subject_numeric_error = $characters_length == 'true' && ! empty( $settings['incomplete_subject'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_subject']) == $subject_length ? stripslashes(esc_attr($settings['incomplete_subject'])) : sprintf( __('Please enter a subject at least %d characters long', 'simpleform' ), $subject_length );
$subject_generic_error = $characters_length != 'true' && ! empty( $settings['incomplete_subject'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_subject']) == '' ? stripslashes(esc_attr($settings['incomplete_subject'])) : esc_attr__('Please type a short and specific subject', 'simpleform' );
$error_subject_label = $characters_length == 'true' ? $subject_numeric_error : $subject_generic_error;
$subject_regex = ! empty( $settings['subject_regex'] ) ? $settings['subject_regex'] : '/^[^\"\/\#$%&()_=+*{}\[\];|<\@>]+$/';
$error_invalid_subject_label = ! empty( $settings['invalid_subject'] ) ? stripslashes(esc_attr($settings['invalid_subject'])) : esc_attr__( 'Enter only alphanumeric characters and punctuation marks', 'simpleform' );
$message_length = ! empty( $settings['message_length'] ) ? esc_attr($settings['message_length']) : '10';
$message_regex = ! empty( $settings['message_regex'] ) ? $settings['message_regex'] : '/^[^\$%&=+*{}|<>]+$/';
$message_numeric_error = $characters_length == 'true' && ! empty( $settings['incomplete_message'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_message']) == $message_length ? stripslashes(esc_attr($settings['incomplete_message'])) : sprintf( __('Please enter a message at least %d characters long', 'simpleform' ), $message_length );
$message_generic_error = $characters_length != 'true' && ! empty( $settings['incomplete_message'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_message']) == '' ? stripslashes(esc_attr($settings['incomplete_message'])) : esc_attr__('Please type a clearer message so we can respond appropriately', 'simpleform' );
$error_message_label = $characters_length == 'true' ? $message_numeric_error : $message_generic_error;
$error_invalid_message_label = ! empty( $settings['invalid_message'] ) ? stripslashes(esc_attr($settings['invalid_message'])) : esc_attr__( 'Enter only alphanumeric characters and punctuation marks', 'simpleform' );
$confirmation_img = SIMPLEFORM_URL . 'public/img/confirmation.png';
$thank_string1 = esc_html__( 'We have received your request!', 'simpleform' );
$thank_string2 = esc_html__( 'Your message will be reviewed soon, and we\'ll get back to you as quickly as possible.', 'simpleform' );
$thank_you_message = '<div id="success-message" class="form confirmation" tabindex="-1"><h4>' . $thank_string1 . '</h4><br>' . $thank_string2 . '</br><img src="'.$confirmation_img.'" alt="message received"></div>';
$blocking_error = ! empty( $settings['blocking_error'] ) ? stripslashes(esc_attr($settings['blocking_error'])) : esc_attr__( 'We are unable to process your request at this time. Please try again later!', 'simpleform' );
$name_numeric_error = $characters_length == 'true' && ! empty( $settings['incomplete_name'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_name']) == $name_length ? stripslashes(esc_attr($settings['incomplete_name'])) : sprintf( __('Please enter at least %d characters', 'simpleform' ), $name_length );
$name_generic_error = $characters_length != 'true' && ! empty( $settings['incomplete_name'] ) && preg_replace('/[^0-9]/', '', $settings['incomplete_name']) == '' ? stripslashes(esc_attr($settings['incomplete_name'])) : esc_attr__('Please type your full name', 'simpleform' );
$error_name_label = $characters_length == 'true' ? $name_numeric_error : $name_generic_error;
$error_email_label = ! empty( $settings['invalid_email'] ) ? stripslashes(esc_attr($settings['invalid_email'])) : esc_attr__( 'Please enter a valid email address', 'simpleform' );
$error_invalid_subject_label = ! empty( $settings['invalid_subject'] ) ? stripslashes(esc_attr($settings['invalid_subject'])) : esc_attr__( 'Enter only alphanumeric characters and punctuation marks', 'simpleform' );
$error_invalid_message_label = ! empty( $settings['invalid_message'] ) ? stripslashes(esc_attr($settings['invalid_message'])) : esc_attr__( 'Enter only alphanumeric characters and punctuation marks', 'simpleform' );
$error_captcha_label = ! empty( $settings['invalid_captcha'] ) ? stripslashes(esc_attr($settings['invalid_captcha'])) : esc_attr__( 'Please enter a valid captcha value', 'simpleform' );
$name_error = ! empty( $settings['name_error'] ) ? stripslashes(esc_attr($settings['name_error'])) : esc_attr__( 'Error occurred validating the name', 'simpleform' );
$email_error = ! empty( $settings['email_error'] ) ? stripslashes(esc_attr($settings['email_error'])) : esc_attr__( 'Error occurred validating the email', 'simpleform' );
$lastname_error = ! empty( $settings['lastname_error'] ) ? stripslashes(esc_attr($settings['lastname_error'])) : esc_attr__( 'Error occurred validating the last name', 'simpleform' );
$phone_error = ! empty( $settings['phone_error'] ) ? stripslashes(esc_attr($settings['phone_error'])) : esc_attr__( 'Error occurred validating the phone number', 'simpleform' );
$subject_error = ! empty( $settings['subject_error'] ) ? stripslashes(esc_attr($settings['subject_error'])) : esc_attr__( 'Error occurred validating the subject', 'simpleform' );
$message_error = ! empty( $settings['message_error'] ) ? stripslashes(esc_attr($settings['message_error'])) : esc_attr__( 'Error occurred validating the message', 'simpleform' );
$consent_error_message = ! empty( $settings['consent_error'] ) ? stripslashes(esc_attr($settings['consent_error'])) : esc_attr__( 'Please accept our privacy policy before submitting form', 'simpleform' );
$captcha_error = ! empty( $settings['captcha_error'] ) ? stripslashes(esc_attr($settings['captcha_error'])) : esc_attr__( 'Error occurred validating the captcha', 'simpleform' );
$honeypot_error = ! empty( $settings['honeypot_error'] ) ? stripslashes(esc_attr($settings['honeypot_error'])) : esc_attr__( 'Failed honeypot validation', 'simpleform' );
$server_error = ! empty( $settings['server_error'] ) ? stripslashes(esc_attr($settings['server_error'])) : esc_attr__( 'Error occurred during processing data. Please try again!', 'simpleform' );
$empty_fields = ! empty( $settings['empty_fields'] ) ? stripslashes(esc_attr($settings['empty_fields'])) : esc_attr__( 'There were some errors that need to be fixed', 'simpleform' );
$empty_name = ! empty( $settings['empty_name'] ) ? stripslashes(esc_attr($settings['empty_name'])) : esc_attr__( 'Please provide your name', 'simpleform' );
$empty_lastname = ! empty( $settings['empty_lastname'] ) ? stripslashes(esc_attr($settings['empty_lastname'])) : esc_attr__( 'Please provide your last name', 'simpleform' );
$empty_phone = ! empty( $settings['empty_phone'] ) ? stripslashes(esc_attr($settings['empty_phone'])) : esc_attr__( 'Please provide your phone number', 'simpleform' );
$empty_email = ! empty( $settings['empty_email'] ) ? stripslashes(esc_attr($settings['empty_email'])) : esc_attr__( 'Please provide your email address', 'simpleform' );
$empty_subject = ! empty( $settings['empty_subject'] ) ? stripslashes(esc_attr($settings['empty_subject'])) : esc_attr__( 'Please enter the request subject', 'simpleform' );
$empty_message = ! empty( $settings['empty_message'] ) ? stripslashes(esc_attr($settings['empty_message'])) : esc_attr__( 'Please enter your message', 'simpleform' );
$empty_captcha = ! empty( $settings['empty_captcha'] ) ? stripslashes(esc_attr($settings['empty_captcha'])) : esc_attr__( 'Please enter an answer', 'simpleform' );
$name_class = isset($error_class['name']) || isset($error_class['name_invalid']) ? 'is-invalid' : '';
$name_attribute = $name_requirement == 'required' ? 'required' : '';
$name_attribute .= $name_maxlength;
$name_value = esc_attr($data['name']);
$name_field_error  = isset($error_class['name']) ? esc_attr($error_name_label) : '';
$name_field_error .= isset($error_class['name_invalid']) ? esc_attr($error_invalid_name_label) : '';
$name_field_error .= !isset($error_class['name']) && !isset($error_class['name_invalid']) ? $empty_name : '';
$lastname_class = isset($error_class['lastname']) || isset($error_class['lastname_invalid']) ? 'is-invalid' : '';
$lastname_attribute = $lastname_requirement == 'required' ? 'required' : '';
$lastname_attribute .= $lastname_maxlength;
$lastname_value = esc_attr($data['lastname']);
$lastname_field_error  = isset($error_class['lastname']) ? esc_attr($error_lastname_label) : '';
$lastname_field_error .= isset($error_class['lastname_invalid']) ? esc_attr($error_invalid_lastname_label) : '';
$lastname_field_error .= !isset($error_class['lastname']) && !isset($error_class['lastname_invalid']) ? $empty_lastname : '';
$email_class = isset($error_class['email']) ? 'is-invalid' : '';
$email_attribute = $email_requirement == 'required' ? 'required' : '';
$email_value = esc_attr($data['email']);
$email_field_error = isset($error_class['email']) ? esc_attr($error_email_label) : '';
$email_field_error .= !isset($error_class['email']) ? $empty_email : '';
$phone_class = isset($error_class['phone']) || isset($error_class['phone_invalid']) ? 'is-invalid' : '';
$phone_attribute = $phone_requirement == 'required' ? 'required' : '';
$phone_value = esc_attr($data['phone']);
$phone_field_error  = isset($error_class['phone']) ? esc_attr($empty_phone) : '';
$phone_field_error .= isset($error_class['phone_invalid']) ? esc_attr($error_phone_label) : '';
$phone_field_error .= !isset($error_class['phone']) && !isset($error_class['phone_invalid']) ? $empty_phone : '';
$subject_class = isset($error_class['subject']) || isset($error_class['subject_invalid']) ? 'is-invalid' : '';
$subject_attribute = $subject_requirement == 'required' ? 'required' : '';
$subject_attribute .= $subject_maxlength;
$subject_value = esc_attr($data['subject']);
$subject_field_error  = isset($error_class['subject']) ? esc_attr($error_subject_label) : '';
$subject_field_error .= isset($error_class['subject_invalid']) ? esc_attr($error_invalid_subject_label) : '';
$subject_field_error .= !isset($error_class['subject']) && !isset($error_class['subject_invalid']) ? $empty_subject : '';
$message_class = isset($error_class['message']) || isset($error_class['message_invalid']) ? 'is-invalid' : '';
$message_value = esc_textarea($data['message']);
$message_field_error  = isset($error_class['message']) ? esc_attr($error_message_label) : '';
$message_field_error .= isset($error_class['message_invalid']) ? esc_attr($error_invalid_message_label) : '';
$message_field_error  .= !isset($error_class['message']) && !isset($error_class['message_invalid']) ? $empty_message : '';
$consent_class = isset($error_class['consent']) ? 'is-invalid' : '';
$consent_attribute = checked($checkbox_value, "true", false);
$consent_requirement = ! empty( $attributes['consent_requirement'] ) && $attributes['consent_requirement'] != 'required' ? '' : ' required';
$consent_attribute .= $consent_requirement;
$captcha_class = isset($error_class['captcha']) ? 'is-invalid' : '';
$captcha_attribute = ' min="11" max="108" data-maxlength="3" oninput="this.value=this.value.slice(0,this.dataset.maxlength)" required';
$captcha_value = esc_attr($data['captcha']);
$captcha_error_class = isset($error_class['captcha']) ? 'd-block' : '';
$captcha_field_error = isset($error_class['captcha']) ? esc_attr($error_captcha_label) : '';
$captcha_field_error .= !isset($error_class['captcha']) ? $empty_captcha : '';
$error_class = ! isset($error_class) ? '' : $error_class; 
$alert_class = ! empty($error_class) ? 'visible' : '';
$form_direction = ! empty( $attributes['form_direction'] ) ? esc_attr($attributes['form_direction']) : 'ltr';
$class_direction = $form_direction == 'rtl' ? 'rtl' : '';
$submit_position = ! empty( $attributes['submit_position'] ) ? esc_attr($attributes['submit_position']) : 'centred';
$html5_validation = ! empty( $settings['html5_validation'] ) ? esc_attr($settings['html5_validation']) : 'false';
$focus = ! empty( $settings['focus'] ) ? esc_attr($settings['focus']) : 'field';
$form_attribute = $html5_validation == 'true' ? ' novalidate' : '';
$form_validation = $html5_validation == 'true' ? 'needs-validation' : '';
$form_focus = $focus != 'alert' ? ' needs-focus' : '';
$form_class = $form_direction == 'rtl' ? 'rtl ' . $form_validation . $form_focus : $form_validation . $form_focus;
$preference_field = ! empty( $attributes['preference_field'] ) ? esc_attr($attributes['preference_field']) : 'hidden';
$preference_label = ! empty( $attributes['preference_label'] ) ? stripslashes(wp_kses_post($attributes['preference_label'])) : '';
$noscript = ! empty($error_class) ? '' : '<noscript><div id="noscript"><span class="message visible">'.esc_attr__('This form needs JavaScript activated to work properly. Please activate it. Thanks!', 'simpleform' ).'</span></div></noscript>';
$outside_error = ! empty( $settings['outside_error'] ) ? esc_attr($settings['outside_error']) : 'bottom';
$error_fields_message = ( ( isset($error_class['name']) || isset($error_class['name_invalid']) ) && $outside_error != 'none' && $errors_counter < 2 ? $name_error : '').''.( ( isset($error_class['lastname']) || isset($error_class['lastname_invalid']) ) && $outside_error != 'none' && $errors_counter < 2 ? $lastname_error : '').''.( isset($error_class['email']) && $outside_error != 'none' && $errors_counter < 2 ? $email_error : '').''.( ( isset($error_class['phone']) || isset($error_class['phone_invalid']) ) && $outside_error != 'none' && $errors_counter < 2 ? $phone_error : '').''.( (isset($error_class['subject']) || isset($error_class['subject_invalid']) ) && $outside_error != 'none' && $errors_counter < 2 ? $subject_error : '').''.( (isset($error_class['message']) || isset($error_class['message_invalid']) ) && $outside_error != 'none' && $errors_counter < 2 ? $message_error : '').''.( isset($error_class['consent']) && $outside_error != 'none' && $errors_counter < 2 ? $consent_error_message : '').''.( isset($error_class['captcha']) && $outside_error != 'none' && $errors_counter < 2 ? $captcha_error : '').''.( isset($error_class['form_honeypot']) && $errors_counter < 2 ? $honeypot_error : '').''.(isset($error_class['server_error']) && $errors_counter < 2 ? $server_error : '');
// array_key_first($error_class)); => $invalid_input = explode('_', array_key_first($error_class))[0];
$script = ! empty($error_class) && $focus == 'field' ? '<script type="text/javascript">window.setTimeout(function(){ document.getElementsByClassName("is-invalid")[0].focus(); }, 0);</script>' : '';
$script .= $errors_counter < 2 && isset($error_class['captcha']) && $focus == 'field' ? '<script type="text/javascript">window.setTimeout(function(){document.getElementById("sform-captcha").focus(); }, 0);</script>' : '';
$script .= (! empty($error_class) && $focus == 'alert') || isset($error_class['server_error']) || isset($error_class['form_honeypot']) ? '<script type="text/javascript">document.getElementById("sform-error").focus();</script>' : '';
$ajax = ! empty( $settings['ajax_submission'] ) ? esc_attr($settings['ajax_submission']) : 'false'; 
$error_script = $ajax == 'false' ? $script : '';
$error_fields_message .= empty($error_class) || $errors_counter > 1 ? $empty_fields : '&nbsp;';
$top_error = $outside_error == 'top' ? '<div id="sform-error" tabindex="-1" class="top '.$wrap_class.'"><span  class="message '.$alert_class.'">'.$error_fields_message.'</span>'.$error_script.$noscript.'</div>' : '';
$bottom_class = $outside_error == 'none' && !isset($error_class['form_honeypot']) && !isset($error_class['server_error']) ? 'invisible '. $alert_class : $alert_class;
$bottom_error = $outside_error != 'top' ? '<div id="sform-error" tabindex="-1" class="'.$wrap_class.'"><span  class="message '.$bottom_class.'">'.$error_fields_message.'</span>'.$error_script.$noscript.'</div>' : '';
$submit_position = ! empty( $attributes['submit_position'] ) ? esc_attr($attributes['submit_position']) : 'centred';
switch ($submit_position) {
case 'left':
$submit_class = "left " . $wrap_class;
$spinner_class = "left";
$button_class = "";
break;
case 'right':
$submit_class = "right " . $wrap_class;
$spinner_class = "right";
$button_class = "";
break;
case 'full':
$submit_class = "full " . $wrap_class;
$spinner_class = "center";
$button_class = "fullwidth";
break;
default:
$submit_class = "center " . $wrap_class;
$spinner_class = "center";
$button_class = "";
}
$spinner = ! empty( $settings['spinner'] ) ? esc_attr($settings['spinner']) : 'false';
$animation = $ajax == 'true' && $spinner == 'true' ? '<div id="spinner" class="d-none '.$spinner_class.'"><div id="bounce1"></div><div id="bounce2"></div><div id="bounce3"></div><div id="bounce4"></div><div id="bounce5"></div></div>' : '';
$focus_confirmation = $ajax != 'true' ? '<script type="text/javascript">document.getElementById("success-message").focus();</script>' : '';